name: 'dwh_project'
version: '1.0.0'

profile: 'dwh_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dwh_project:
    +materialized: view  # Make sure this matches your expected schema
