seeds:
  - name: zip_codes
    config:
      column_types:
        zipcode: varchar
        name: varchar
  - name: psvfile
    config:
      delimiter: "|"
      column_types:
        id: number
        name: varchar
  - name: Countrydialcode
    config:
      column_types:
        COUNTRY: varchar(30)
        COUNTRY_CODE: Number
        dialcode:
          countrycode2:
            column_types:
              COUNTRY: varchar(30)
              COUNTRY_CODE: Number