name: dbt CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dbt_ci_cd:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment for dbt
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install dbt-core and required dependencies
      - name: Install dbt-core
        run: |
          python -m pip install --upgrade pip setuptools
          pip install dbt-core dbt-snowflake  # Install dbt for Snowflake

      # Step 4: Create the dbt profiles.yml file from GitHub Secrets
      - name: Set up dbt profiles.yml
        run: |
          mkdir -p ~/.dbt
          echo "$DBT_PROFILES_YML" > ~/.dbt/profiles.yml
        env:
          DBT_PROFILES_YML: ${{ secrets.DBT_PROFILES_YML }}

      # Step 5: Verify dbt installation
      - name: Verify dbt installation
        run: dbt --version

      # Step 6: Check Snowflake connection
      - name: Run dbt debug
        run: dbt debug

      # Step 7: Install dbt dependencies
      - name: Install dbt dependencies
        run: dbt deps

      # Step 8: Run dbt models
      - name: Run dbt models
        run: dbt run

      # Step 9: Run dbt tests
      - name: Run dbt tests
        run: dbt test

      # Step 10: Generate dbt documentation
      - name: Generate dbt documentation
        run: dbt docs generate

      # Step 11: Upload dbt artifacts for review
      - name: Upload dbt artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dbt-artifacts
          path: target/
