name: dbt CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dbt_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Upgrade pip & Install dbt
        run: |
          python -m pip install --upgrade pip setuptools
          pip install dbt-core  # Only dbt-core, no adapters

      - name: Verify dbt installation
        run: dbt --version

      - name: Install dbt dependencies
        run: dbt deps

      - name: Run dbt models
        run: dbt run

      - name: Run dbt tests
        run: dbt test

      - name: Generate dbt documentation
        run: dbt docs generate

      - name: Upload dbt artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dbt-artifacts
          path: target/
