name: dbt CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dbt_run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install dbt-core
      - name: Install dbt-core
        run: |
          python -m pip install --upgrade pip setuptools
          pip install --user dbt-core dbt-snowflake

      # Step 4: Set up dbt profiles.yml (from GitHub Secrets)
      - name: Set up dbt profiles.yml
        run: |
          mkdir -p ~/.dbt  # Ensure the .dbt directory exists
          echo "${{ secrets.DBT_PROFILES }}" > ~/.dbt/profiles.yml

      # Step 5: Verify dbt installation
      - name: Verify dbt installation
        run: |
          echo "Checking dbt version..."
          ~/.local/bin/dbt --version

      # Step 6: Install dbt dependencies
      - name: Install dbt dependencies
        run: ~/.local/bin/dbt deps

      # Step 7: Run dbt models
      - name: Run dbt models
        run: ~/.local/bin/dbt run

      # Step 8: Run dbt tests
      - name: Run dbt tests
        run: ~/.local/bin/dbt test

      # Step 9: Generate dbt documentation
      - name: Generate dbt documentation
        run: ~/.local/bin/dbt docs generate

      # Step 10: Upload dbt artifacts
      - name: Upload dbt artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dbt-artifacts
          path: target/
