name: dbt CI/CD Pipeline  # Workflow name

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to main branch

jobs:
  dbt_run:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner environment

    steps:
      # Step 1: Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Use Python 3.9

      # Step 3: Install dbt-core
      - name: Install dbt-core
        run: |
          python -m pip install --upgrade pip setuptools
          pip install dbt-core  # Install dbt-core globally

      # Step 4: Verify dbt installation
      - name: Verify dbt installation
        run: dbt --version  # Confirm dbt is installed

      # Step 5: Create profiles.yml dynamically (Dummy Credentials for Reference)
      - name: Configure dbt profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          my_snowflake_profile:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: qkluqag-to07768.snowflakecomputing.com
                user: shree
                password: Srikanth1296!?!
                role: ACCOUNTADMIN 
                database: classicmodels
                warehouse: compute_wh
                schema: raw
                threads: 4
          EOF

      # Step 6: Install dbt dependencies
      - name: Install dbt dependencies
        run: dbt deps

      # Step 7: Run dbt models
      - name: Run dbt models
        run: dbt run

      # Step 8: Run dbt tests
      - name: Run dbt tests
        run: dbt test

      # Step 9: Generate dbt documentation
      - name: Generate dbt documentation
        run: dbt docs generate

      # Step 10: Upload dbt artifacts (logs, compiled files, test results)
      - name: Upload dbt artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dbt-artifacts
          path: target/
